project:
  type: website

website:
  title: "Streamflow Forecasting Onboarding"
  site-url: https://csiro-hydroinformatics.github.io/streamflow-forecasting-tools-onboard/
  favicon: ./img/favicon.png  
  image: ./img/favicon.png  

  page-footer: 
    right: "This page is built with [Quarto](https://quarto.org/)"
    left: "&copy; CC-By CSIRO"

  navbar:
    logo: ./img/favicon.png
    href: https://csiro-hydroinformatics.github.io/streamflow-forecasting-tools-onboard/
    title: false
    collapse-below: lg
    left:
      - text: Home
        href: index.qmd
      # - text: "About"
      #   href: about.qmd
      - text: "Installation"
        href: installation.qmd
      - text: "Documentation"
        href: documentation.qmd
      - text: "FAQ"
        href: faq.qmd
      # - text: "Cookbook"
      #   href: cookbook-navbar-page.qmd
      # - text: "Events"
      #   href: events.qmd
    right:
      - icon: github
        href: https://github.com/csiro-hydroinformatics/
      # - icon: twitter
      #   href: https://twitter.com/openscapes

  sidebar:
    - id: installation
      title: "Installation"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - installation.qmd
        - text: "Installation: Windows"
          href: doc/installation/install_windows.qmd
        - text: "Installation: Debian based Linux"
          href: doc/installation/install_linux.qmd
        - text: "Installation: MacOSX"
          href: doc/installation/install_macosx.qmd
        - text: "Installation: via Docker"
          href: doc/installation/install_docker.qmd
    - id: documentation
      title: "Documentation"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - documentation.qmd
        - section: "Examples in R"
          href: doc/samples/sample_workflows_r.md
          contents:
            - doc/samples/R/vignettes/getting_started/getting_started.md
            - doc/samples/R/vignettes/ensemble_model_runs/ensemble_model_runs.md
            - doc/samples/R/vignettes/ensemble_forecast_model_runs/ensemble_forecast_model_runs.md
            - doc/samples/R/vignettes/meta_parameters/meta_parameters.md
            - doc/samples/R/vignettes/calibrate_multisite/calibrate_multisite.md
            - doc/samples/R/vignettes/calibrate_subcatchments/calibrate_subcatchments.md
            - doc/samples/R/vignettes/calibration_initial_states/calibration_initial_states.md
            - doc/samples/R/vignettes/error_correction_four_stages/error_correction_four_stages.md
            - doc/samples/R/vignettes/muskingum_multilink_calibration/muskingum_multilink_calibration.md
        - text: "Developer documentation"
          href: doc/developer.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    highlight-style: breeze
    toc: true
    toc-title: Contents
    toc-location: right


