---
title: "Documentation"
---

Pointers to further technical documentation for using or developing features.

# Sample workflows for modellers

* [vignettes for the `swift` package](./doc/samples/sample_workflows_r.md)
* [jupyter notebooks for the python package `swift2`](https://csiro-hydroinformatics.github.io/swift-py-doc/notebooks/getting_started/){.external target="_blank"}
* [basic matlab example](./doc/samples/sample_workflows_matlab.qmd)

# Technical references

## Packages documentations

The [python package swift2](https://csiro-hydroinformatics.github.io/swift-py-doc){.external target="_blank"} is the latest (from ~2020) implementation of python access arrangements to the "swift2" engine for semi-distributed streamflow modelling and forecasting. The [uchronia time series API documentation](https://csiro-hydroinformatics.github.io/uchronia-ts-doc){.external target="_blank"} combines the documentation of the python package `uchronia` with its C++ core. Other packages include "docstrings" available to users for reference, but are not yet published on the Web.

The R packages in the software distribution contain function documentation, example code snippets and so-called "vignettes". These are not yet published via web sites. You can access vignettes in the packages for instance with the following statements in an `R` terminal:

```R
library(swift)
library(uchronia)
browseVignettes('swift')
```

You can access the wider package documentation using the command `?swift`, and see an index of the features by navigating down the page to the footer `[Package swift version 2.4.x Index]`. Click on the `Index` hyperlink of that footer. Note that you will find a very long list of functions, but note that functions postfixed `_R` should not be used as primary building blocks in your scripts.

## Build pipelines

Software build pipelines have been devised to streamline the compilation, testing and packaging of software artifacts. See [build workflows](./doc/build.qmd) for details. 

# Publications

[SWIFT2: High performance software for short-medium term ensemble streamflow forecasting research and operations](https://www.mssanz.org.au/modsim2015/L15/perraud.pdf){.external target="_blank"}

[SWIFT2: Advanced software for continuous ensemble short-term streamflow forecasting ](https://search.informit.com.au/documentSummary;dn=823693257390059;res=IELENG){.external target="_blank"}
