---
title: "Build workflows"
---

This page is an overview of the workflows devised to build the software stack (compile, package, version, document, etc.).

## Building installers

Not counting third party established libraries such as Boost, a dozen git repositories under our control are used as inputs to the pipelines that package the software stack. Maintaining versions within each of these repositories may be influenced by various factors including unrelated projects, not necessarily solely by these installers. We are using the commit hashsums of this dozen of repositories to record and specify which version of each repositories is used as input to the build pipelines (see Fig. 1)

```{mermaid}
%%| label: fig-simple
%%| fig-cap: Package build workflow.

flowchart TD
  A[code freeze] --> B{unit testing}
  B -->|Yes| C[git tag]
  B -->|No| A
  C -->D[/commit hashsums in git repositories/] 
  D --> E[Linux build]
  D --> F[MacOSX build]
  E --> G[Win build]

  E -->H[/.deb, python wheels \nand R tarballs/] 
  G -->I[/.dll, R binary \ninstallers for windows/] 
  F -->J[/.dylib, homebrew packages/] 

```

## Versioning

This is a (partly populated) placeholder section to document the rationale for versioning installer bundles, and components at a final granularity.

There may be a versioning, semantic or otherwise, used for the bundles of installers produced for various platforms (Fig. 1). The major product is still what used to be refered to as SWIFT2, but there are also other important, related but distinct, products (FoGSS, CHyPP) also. 

### 

## Channels for software distribution

Some software such as the [refcount](https://pyrefcount.readthedocs.io) python package are available via [conda-forge](https://github.com/conda-forge/refcount-feedstock/) and [pypi](https://pypi.org/project/refcount/). We cannot use these mechanism for closed source packages, but we may consider in the future distribution via:

* "private" conda channel
* "private" pypi repository
* "private" debian package repository
* "private" homebrew package repository (MacOSX)